version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=dev
    command: ["redis-server", "--requirepass", "dev"]
    restart: unless-stopped
