quarkus.http.port=8080
quarkus.http.root-path=/api/v1/redis-management

quarkus.redis.hosts=redis://localhost:6380
quarkus.redis.tls.enabled=false
quarkus.redis.password=dev2

quarkus.smallrye-health.enabled=true